nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.1_seed1 --numpy-rand-seed 1 --optimizer adagrad --tensor-board-filename adagrad_lr0.1_seed1  --test-freq 1024 > 0611_adagrad_lr0.1_seed1.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.1_seed2 --numpy-rand-seed 2 --optimizer adagrad --tensor-board-filename adagrad_lr0.1_seed2  --test-freq 1024 > 0611_adagrad_lr0.1_seed2.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.1_seed2 --numpy-rand-seed 3 --optimizer adagrad --tensor-board-filename adagrad_lr0.1_seed3  --test-freq 1024 > 0611_adagrad_lr0.1_seed3.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.5 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.5_seed1 --numpy-rand-seed 1 --optimizer adagrad --tensor-board-filename adagrad_lr0.5_seed1  --test-freq 1024 > 0611_adagrad_lr0.5_seed1.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.5 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.5_seed2 --numpy-rand-seed 2 --optimizer adagrad --tensor-board-filename adagrad_lr0.5_seed2  --test-freq 1024 > 0611_adagrad_lr0.5_seed2.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.5 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr0.5_seed2 --numpy-rand-seed 3 --optimizer adagrad --tensor-board-filename adagrad_lr0.5_seed3  --test-freq 1024 > 0611_adagrad_lr0.5_seed3.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr1_seed1 --numpy-rand-seed 1 --optimizer adagrad --tensor-board-filename adagrad_lr1_seed1  --test-freq 1024 > 0611_adagrad_lr1_seed1.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr1_seed2 --numpy-rand-seed 2 --optimizer adagrad --tensor-board-filename adagrad_lr1_seed2  --test-freq 1024 > 0611_adagrad_lr1_seed2.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr1_seed2 --numpy-rand-seed 3 --optimizer adagrad --tensor-board-filename adagrad_lr1_seed3  --test-freq 1024 > 0611_adagrad_lr1_seed3.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=2 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr2_seed1 --numpy-rand-seed 1 --optimizer adagrad --tensor-board-filename adagrad_lr2_seed1  --test-freq 1024 > 0611_adagrad_lr2_seed1.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=2 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr2_seed2 --numpy-rand-seed 2 --optimizer adagrad --tensor-board-filename adagrad_lr2_seed2  --test-freq 1024 > 0611_adagrad_lr2_seed2.out &

nohup python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=2 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model-dir model_adagrad_lr2_seed2 --numpy-rand-seed 3 --optimizer adagrad --tensor-board-filename adagrad_lr2_seed3  --test-freq 1024 > 0611_adagrad_lr2_seed3.out &


